-- Divine Manager (Big Pimping): settings and tasks for the meta-orchestrator

-- Manager mode enum
DO $$ BEGIN
  CREATE TYPE divine_manager_mode AS ENUM ('off', 'suggest_only', 'semi_auto');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Manager task status enum
DO $$ BEGIN
  CREATE TYPE divine_manager_task_status AS ENUM ('suggested', 'scheduled', 'executed', 'skipped', 'failed');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- One row per user: persona, goals, automation rules, mode
CREATE TABLE IF NOT EXISTS public.divine_manager_settings (
  user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  persona JSONB DEFAULT '{}',
  goals JSONB DEFAULT '{}',
  automation_rules JSONB DEFAULT '{}',
  mode divine_manager_mode NOT NULL DEFAULT 'off',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tasks generated by workers / AI (suggestions, scheduled actions, log)
CREATE TABLE IF NOT EXISTS public.divine_manager_tasks (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  status divine_manager_task_status NOT NULL DEFAULT 'suggested',
  payload JSONB DEFAULT '{}',
  source TEXT,
  scheduled_for TIMESTAMPTZ,
  executed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_divine_manager_tasks_user_id ON public.divine_manager_tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_divine_manager_tasks_status ON public.divine_manager_tasks(status);
CREATE INDEX IF NOT EXISTS idx_divine_manager_tasks_scheduled_for ON public.divine_manager_tasks(scheduled_for) WHERE scheduled_for IS NOT NULL;

-- RLS
ALTER TABLE public.divine_manager_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.divine_manager_tasks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage own divine_manager_settings" ON public.divine_manager_settings;
CREATE POLICY "Users can manage own divine_manager_settings" ON public.divine_manager_settings
  FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can manage own divine_manager_tasks" ON public.divine_manager_tasks;
CREATE POLICY "Users can manage own divine_manager_tasks" ON public.divine_manager_tasks
  FOR ALL USING (auth.uid() = user_id);
